"""create initial screening schema

Revision ID: 3596cb85451b
Revises: 
Create Date: 2026-08-16 12:30:33.283275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3596cb85451b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('education_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_experience_months', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('job_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organizations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_experience_months', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_resume_id'), 'resumes', ['resume_id'], unique=True)
    op.create_table('resume_education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_education_resume_id'), 'resume_education', ['resume_id'], unique=False)
    op.create_table('resume_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_experiences_resume_id'), 'resume_experiences', ['resume_id'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('eligibility_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('decision_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'resume_id', name='uq_screening_job_resume')
    )
    op.create_index(op.f('ix_screening_results_job_id'), 'screening_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_screening_results_resume_id'), 'screening_results', ['resume_id'], unique=False)
    op.create_table('match_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('gap_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screening_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_profiles_screening_id'), 'match_profiles', ['screening_id'], unique=True)
    op.create_table('ranking_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('seniority_score', sa.Float(), nullable=False),
    sa.Column('education_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screening_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_results_screening_id'), 'ranking_results', ['screening_id'], unique=True)
    op.create_table('evidence_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['match_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_references_profile_id'), 'evidence_references', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_references_profile_id'), table_name='evidence_references')
    op.drop_table('evidence_references')
    op.drop_index(op.f('ix_ranking_results_screening_id'), table_name='ranking_results')
    op.drop_table('ranking_results')
    op.drop_index(op.f('ix_match_profiles_screening_id'), table_name='match_profiles')
    op.drop_table('match_profiles')
    op.drop_index(op.f('ix_screening_results_resume_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_job_id'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_resume_experiences_resume_id'), table_name='resume_experiences')
    op.drop_table('resume_experiences')
    op.drop_index(op.f('ix_resume_education_resume_id'), table_name='resume_education')
    op.drop_table('resume_education')
    op.drop_index(op.f('ix_resumes_resume_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
