/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screen Candidates */
        post: operations["screen_candidates_api_screen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranking/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank Candidates For Job */
        post: operations["rank_candidates_for_job_api_ranking__job_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs Endpoint */
        get: operations["list_jobs_endpoint_api_jobs_get"];
        put?: never;
        /** Create Job Endpoint */
        post: operations["create_job_endpoint_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job From File Endpoint */
        post: operations["create_job_from_file_endpoint_api_jobs_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Endpoint */
        get: operations["get_job_endpoint_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job Endpoint */
        delete: operations["delete_job_endpoint_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Job Endpoint */
        post: operations["close_job_endpoint_api_jobs__job_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes Endpoint */
        get: operations["list_resumes_endpoint_api_resumes_get"];
        put?: never;
        /** Create Resume Endpoint */
        post: operations["create_resume_endpoint_api_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume Endpoint */
        get: operations["get_resume_endpoint_api_resumes__resume_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenings/{job_id}/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screening */
        get: operations["get_screening_api_screenings__job_id___resume_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenings/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Screenings */
        get: operations["list_screenings_api_screenings__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Auth
         * @description Exchange a verified Google ID token for the application's own
         *     JWT - the same token type/shape issued by password login. The
         *     Google credential itself is never used as, or returned as, an
         *     application access token.
         */
        post: operations["google_auth_api_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Available Jobs */
        get: operations["list_available_jobs_api_candidate_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Available Job */
        get: operations["get_available_job_api_candidate_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate/resumes/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Resume */
        post: operations["upload_resume_api_candidate_resumes_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Resumes */
        get: operations["list_my_resumes_api_candidate_resumes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate/jobs/{job_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Match */
        post: operations["preview_match_api_candidate_jobs__job_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate/jobs/{job_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply To Job */
        post: operations["apply_to_job_api_candidate_jobs__job_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Applications */
        get: operations["list_my_applications_api_candidate_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidate/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Application */
        get: operations["get_my_application_api_candidate_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Applications */
        get: operations["list_job_applications_api_jobs__job_id__applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Application */
        get: operations["get_job_application_api_jobs__job_id__applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Status */
        patch: operations["update_status_api_applications__application_id__status_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationResponse */
        ApplicationResponse: {
            /** Application Id */
            application_id: number;
            /** Job Id */
            job_id: string;
            /** Job Title */
            job_title: string | null;
            /** Resume Id */
            resume_id: string;
            /** Candidate Name */
            candidate_name: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "shortlisted" | "rejected" | "withdrawn";
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            screening: components["schemas"]["ScreeningResultResponse"] | null;
        };
        /** ApplicationStatusUpdateRequest */
        ApplicationStatusUpdateRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "shortlisted" | "rejected" | "withdrawn";
        };
        /** ApplyRequest */
        ApplyRequest: {
            /** Resume Id */
            resume_id: string;
        };
        /** Body_create_job_from_file_endpoint_api_jobs_upload_post */
        Body_create_job_from_file_endpoint_api_jobs_upload_post: {
            /** Title */
            title?: string | null;
            /** File */
            file: string;
        };
        /** Body_upload_resume_api_candidate_resumes_upload_post */
        Body_upload_resume_api_candidate_resumes_upload_post: {
            /** File */
            file: string;
        };
        /** CandidateJobDetail */
        CandidateJobDetail: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string | null;
            /** Location */
            location: string | null;
            /** Job Type */
            job_type: string | null;
            /** Required Skills */
            required_skills: string[];
            /** Required Experience Months */
            required_experience_months: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Raw Text */
            raw_text: string;
            /** Preferred Skills */
            preferred_skills: string[];
            /** Required Technologies */
            required_technologies: string[];
        };
        /** CandidateJobSummary */
        CandidateJobSummary: {
            /** Job Id */
            job_id: string;
            /** Title */
            title: string | null;
            /** Location */
            location: string | null;
            /** Job Type */
            job_type: string | null;
            /** Required Skills */
            required_skills: string[];
            /** Required Experience Months */
            required_experience_months: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Education */
        Education: {
            /** Institution */
            institution?: string | null;
            /** Degree */
            degree?: string | null;
            /** Field */
            field?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** Experience */
        Experience: {
            /** Company */
            company?: string | null;
            /** Role */
            role?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Description */
            description?: string | null;
        };
        /** GoogleAuthRequest */
        GoogleAuthRequest: {
            /** Credential */
            credential: string;
            /** Role */
            role?: ("recruiter" | "candidate") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Job Id */
            job_id: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Job Type */
            job_type?: string | null;
            /** Raw Text */
            raw_text: string;
            /** Required Skills */
            required_skills?: string[];
            /** Preferred Skills */
            preferred_skills?: string[];
            /** Required Technologies */
            required_technologies?: string[];
            /** Preferred Technologies */
            preferred_technologies?: string[];
            /** Education Requirements */
            education_requirements?: {
                [key: string]: unknown;
            }[];
            /** Required Certifications */
            required_certifications?: string[];
            /**
             * Required Experience Months
             * @default 0
             */
            required_experience_months: number;
        };
        /** JobDescription */
        JobDescription: {
            /** Job Id */
            job_id: string;
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Required Skills */
            required_skills?: string[];
            /** Preferred Skills */
            preferred_skills?: string[];
            /** Required Experience Years */
            required_experience_years?: number | null;
            /** Education */
            education?: string[];
            /** Certifications */
            certifications?: string[];
            /** Responsibilities */
            responsibilities?: string[];
            /** Location */
            location?: string | null;
            /** Job Type */
            job_type?: string | null;
            /** Raw Text */
            raw_text: string;
        };
        /** JobResponse */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Job Type */
            job_type?: string | null;
            /** Raw Text */
            raw_text: string;
            /** Required Skills */
            required_skills: string[];
            /** Preferred Skills */
            preferred_skills: string[];
            /** Required Technologies */
            required_technologies: string[];
            /** Preferred Technologies */
            preferred_technologies: string[];
            /** Education Requirements */
            education_requirements: {
                [key: string]: unknown;
            }[];
            /** Required Certifications */
            required_certifications: string[];
            /** Required Experience Months */
            required_experience_months: number;
            /**
             * Status
             * @default open
             */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RecruiterApplicationListItem */
        RecruiterApplicationListItem: {
            /** Application Id */
            application_id: number;
            /** Resume Id */
            resume_id: string;
            /** Candidate Name */
            candidate_name: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "shortlisted" | "rejected" | "withdrawn";
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Rank */
            rank: number | null;
            /** Score */
            score: number | null;
            /** Eligible */
            eligible: boolean | null;
            /** Decision */
            decision: string | null;
        };
        /** RecruiterApplicationListResponse */
        RecruiterApplicationListResponse: {
            /** Job Id */
            job_id: string;
            /** Total Applications */
            total_applications: number;
            /** Results */
            results: components["schemas"]["RecruiterApplicationListItem"][];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default recruiter
             * @enum {string}
             */
            role: "recruiter" | "candidate";
        };
        /** Resume */
        Resume: {
            /** Resume Id */
            resume_id: string;
            /** Name */
            name?: string | null;
            /** Summary */
            summary?: string | null;
            /** Skills */
            skills?: string[];
            /** Experience */
            experience?: components["schemas"]["Experience"][];
            /** Education */
            education?: components["schemas"]["Education"][];
            /** Certifications */
            certifications?: string[];
            /** Projects */
            projects?: string[];
            /** Job Titles */
            job_titles?: string[];
            /** Total Experience Years */
            total_experience_years?: number | null;
            /** Raw Text */
            raw_text: string;
        };
        /** ResumeCreateRequest */
        ResumeCreateRequest: {
            /** Resume Id */
            resume_id: string;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Summary */
            summary?: string | null;
            /** Skills */
            skills?: string[];
            /** Job Titles */
            job_titles?: string[];
            /** Organizations */
            organizations?: string[];
            /** Technologies */
            technologies?: string[];
            /**
             * Total Experience Months
             * @default 0
             */
            total_experience_months: number;
            /** Raw Text */
            raw_text?: string | null;
            /** Experiences */
            experiences?: components["schemas"]["ResumeExperienceCreate"][];
            /** Education */
            education?: components["schemas"]["ResumeEducationCreate"][];
        };
        /** ResumeEducationCreate */
        ResumeEducationCreate: {
            /** Degree */
            degree: string;
            /** Institution */
            institution: string;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ResumeEducationResponse */
        ResumeEducationResponse: {
            /** Degree */
            degree: string;
            /** Institution */
            institution: string;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Id */
            id: number;
        };
        /** ResumeExperienceCreate */
        ResumeExperienceCreate: {
            /** Job Title */
            job_title: string;
            /** Company */
            company: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Duration Months
             * @default 0
             */
            duration_months: number;
        };
        /** ResumeExperienceResponse */
        ResumeExperienceResponse: {
            /** Job Title */
            job_title: string;
            /** Company */
            company: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Duration Months
             * @default 0
             */
            duration_months: number;
            /** Id */
            id: number;
        };
        /** ResumeResponse */
        ResumeResponse: {
            /** Resume Id */
            resume_id: string;
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Summary */
            summary: string | null;
            /** Skills */
            skills: string[];
            /** Job Titles */
            job_titles: string[];
            /** Organizations */
            organizations: string[];
            /** Technologies */
            technologies: string[];
            /** Total Experience Months */
            total_experience_months: number;
            /** Raw Text */
            raw_text: string | null;
            /** Experiences */
            experiences: components["schemas"]["ResumeExperienceResponse"][];
            /** Education */
            education: components["schemas"]["ResumeEducationResponse"][];
        };
        /** ScreeningListResponse */
        ScreeningListResponse: {
            /** Job Id */
            job_id: string;
            /** Total Candidates */
            total_candidates: number;
            /** Results */
            results: components["schemas"]["ScreeningResultResponse"][];
        };
        /** ScreeningRequest */
        ScreeningRequest: {
            job_description: components["schemas"]["JobDescription"];
            /** Resumes */
            resumes?: components["schemas"]["Resume"][];
        };
        /** ScreeningResponse */
        ScreeningResponse: {
            /** Job Id */
            job_id: string;
            /** Total Candidates */
            total_candidates: number;
            /** Eligible Candidates */
            eligible_candidates: number;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** ScreeningResultResponse */
        ScreeningResultResponse: {
            /** Screening Id */
            screening_id: number;
            /** Job Id */
            job_id: string;
            /** Resume Id */
            resume_id: string;
            /** Candidate Name */
            candidate_name?: string | null;
            /** Eligible */
            eligible: boolean;
            /** Decision */
            decision: string | null;
            /** Final Score */
            final_score: number | null;
            /** Decision Reason */
            decision_reason: string | null;
            /** Ranking */
            ranking?: {
                [key: string]: unknown;
            } | null;
            /** Gap Analysis */
            gap_analysis?: {
                [key: string]: unknown;
            } | null;
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            } | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "recruiter" | "viewer" | "candidate";
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    screen_candidates_api_screen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreeningRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_candidates_for_job_api_ranking__job_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_endpoint_api_jobs_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_endpoint_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_from_file_endpoint_api_jobs_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_from_file_endpoint_api_jobs_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_endpoint_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_endpoint_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_job_endpoint_api_jobs__job_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resumes_endpoint_api_resumes_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resume_endpoint_api_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_endpoint_api_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_api_screenings__job_id___resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_screenings_api_screenings__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_auth_api_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_available_jobs_api_candidate_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateJobSummary"][];
                };
            };
        };
    };
    get_available_job_api_candidate_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateJobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_resume_api_candidate_resumes_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_resume_api_candidate_resumes_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_resumes_api_candidate_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"][];
                };
            };
        };
    };
    preview_match_api_candidate_jobs__job_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_to_job_api_candidate_jobs__job_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_applications_api_candidate_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"][];
                };
            };
        };
    };
    get_my_application_api_candidate_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_applications_api_jobs__job_id__applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecruiterApplicationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_application_api_jobs__job_id__applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_api_applications__application_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
