/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Screen Candidates */
        post: operations["screen_candidates_api_screen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ranking/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank Candidates For Job */
        post: operations["rank_candidates_for_job_api_ranking__job_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs Endpoint */
        get: operations["list_jobs_endpoint_api_jobs_get"];
        put?: never;
        /** Create Job Endpoint */
        post: operations["create_job_endpoint_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Endpoint */
        get: operations["get_job_endpoint_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes Endpoint */
        get: operations["list_resumes_endpoint_api_resumes_get"];
        put?: never;
        /** Create Resume Endpoint */
        post: operations["create_resume_endpoint_api_resumes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume Endpoint */
        get: operations["get_resume_endpoint_api_resumes__resume_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenings/{job_id}/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screening */
        get: operations["get_screening_api_screenings__job_id___resume_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenings/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Screenings */
        get: operations["list_screenings_api_screenings__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Education */
        Education: {
            /** Institution */
            institution?: string | null;
            /** Degree */
            degree?: string | null;
            /** Field */
            field?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** Experience */
        Experience: {
            /** Company */
            company?: string | null;
            /** Role */
            role?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Job Id */
            job_id: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Job Type */
            job_type?: string | null;
            /** Raw Text */
            raw_text: string;
            /** Required Skills */
            required_skills?: string[];
            /** Preferred Skills */
            preferred_skills?: string[];
            /** Required Technologies */
            required_technologies?: string[];
            /** Preferred Technologies */
            preferred_technologies?: string[];
            /** Education Requirements */
            education_requirements?: {
                [key: string]: unknown;
            }[];
            /** Required Certifications */
            required_certifications?: string[];
            /**
             * Required Experience Months
             * @default 0
             */
            required_experience_months: number;
        };
        /** JobDescription */
        JobDescription: {
            /** Job Id */
            job_id: string;
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Required Skills */
            required_skills?: string[];
            /** Preferred Skills */
            preferred_skills?: string[];
            /** Required Experience Years */
            required_experience_years?: number | null;
            /** Education */
            education?: string[];
            /** Certifications */
            certifications?: string[];
            /** Responsibilities */
            responsibilities?: string[];
            /** Location */
            location?: string | null;
            /** Job Type */
            job_type?: string | null;
            /** Raw Text */
            raw_text: string;
        };
        /** JobResponse */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Location */
            location?: string | null;
            /** Job Type */
            job_type?: string | null;
            /** Raw Text */
            raw_text: string;
            /** Required Skills */
            required_skills: string[];
            /** Preferred Skills */
            preferred_skills: string[];
            /** Required Technologies */
            required_technologies: string[];
            /** Preferred Technologies */
            preferred_technologies: string[];
            /** Education Requirements */
            education_requirements: {
                [key: string]: unknown;
            }[];
            /** Required Certifications */
            required_certifications: string[];
            /** Required Experience Months */
            required_experience_months: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Resume */
        Resume: {
            /** Resume Id */
            resume_id: string;
            /** Name */
            name?: string | null;
            /** Summary */
            summary?: string | null;
            /** Skills */
            skills?: string[];
            /** Experience */
            experience?: components["schemas"]["Experience"][];
            /** Education */
            education?: components["schemas"]["Education"][];
            /** Certifications */
            certifications?: string[];
            /** Projects */
            projects?: string[];
            /** Job Titles */
            job_titles?: string[];
            /** Total Experience Years */
            total_experience_years?: number | null;
            /** Raw Text */
            raw_text: string;
        };
        /** ResumeCreateRequest */
        ResumeCreateRequest: {
            /** Resume Id */
            resume_id: string;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Summary */
            summary?: string | null;
            /** Skills */
            skills?: string[];
            /** Job Titles */
            job_titles?: string[];
            /** Organizations */
            organizations?: string[];
            /** Technologies */
            technologies?: string[];
            /**
             * Total Experience Months
             * @default 0
             */
            total_experience_months: number;
            /** Raw Text */
            raw_text?: string | null;
            /** Experiences */
            experiences?: components["schemas"]["ResumeExperienceCreate"][];
            /** Education */
            education?: components["schemas"]["ResumeEducationCreate"][];
        };
        /** ResumeEducationCreate */
        ResumeEducationCreate: {
            /** Degree */
            degree: string;
            /** Institution */
            institution: string;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** ResumeEducationResponse */
        ResumeEducationResponse: {
            /** Degree */
            degree: string;
            /** Institution */
            institution: string;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Id */
            id: number;
        };
        /** ResumeExperienceCreate */
        ResumeExperienceCreate: {
            /** Job Title */
            job_title: string;
            /** Company */
            company: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Duration Months
             * @default 0
             */
            duration_months: number;
        };
        /** ResumeExperienceResponse */
        ResumeExperienceResponse: {
            /** Job Title */
            job_title: string;
            /** Company */
            company: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Duration Months
             * @default 0
             */
            duration_months: number;
            /** Id */
            id: number;
        };
        /** ResumeResponse */
        ResumeResponse: {
            /** Resume Id */
            resume_id: string;
            /** Name */
            name: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Summary */
            summary: string | null;
            /** Skills */
            skills: string[];
            /** Job Titles */
            job_titles: string[];
            /** Organizations */
            organizations: string[];
            /** Technologies */
            technologies: string[];
            /** Total Experience Months */
            total_experience_months: number;
            /** Raw Text */
            raw_text: string | null;
            /** Experiences */
            experiences: components["schemas"]["ResumeExperienceResponse"][];
            /** Education */
            education: components["schemas"]["ResumeEducationResponse"][];
        };
        /** ScreeningListResponse */
        ScreeningListResponse: {
            /** Job Id */
            job_id: string;
            /** Total Candidates */
            total_candidates: number;
            /** Results */
            results: components["schemas"]["ScreeningResultResponse"][];
        };
        /** ScreeningRequest */
        ScreeningRequest: {
            job_description: components["schemas"]["JobDescription"];
            /** Resumes */
            resumes?: components["schemas"]["Resume"][];
        };
        /** ScreeningResponse */
        ScreeningResponse: {
            /** Job Id */
            job_id: string;
            /** Total Candidates */
            total_candidates: number;
            /** Eligible Candidates */
            eligible_candidates: number;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
        };
        /** ScreeningResultResponse */
        ScreeningResultResponse: {
            /** Screening Id */
            screening_id: number;
            /** Job Id */
            job_id: string;
            /** Resume Id */
            resume_id: string;
            /** Candidate Name */
            candidate_name?: string | null;
            /** Eligible */
            eligible: boolean;
            /** Decision */
            decision: string | null;
            /** Final Score */
            final_score: number | null;
            /** Decision Reason */
            decision_reason: string | null;
            /** Ranking */
            ranking?: {
                [key: string]: unknown;
            } | null;
            /** Gap Analysis */
            gap_analysis?: {
                [key: string]: unknown;
            } | null;
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            } | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    screen_candidates_api_screen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreeningRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rank_candidates_for_job_api_ranking__job_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_endpoint_api_jobs_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_endpoint_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_endpoint_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resumes_endpoint_api_resumes_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resume_endpoint_api_resumes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_endpoint_api_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_api_screenings__job_id___resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_screenings_api_screenings__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
