"""
Dense vector retrieval for semantic resume matching.

Uses FAISS for efficient vector similarity search and aggregates
chunk-level similarities into candidate-level results.

BGE-M3 embeddings are normalized, so FAISS inner-product search
is equivalent to cosine similarity.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import faiss
import numpy as np

from app.retrieval.embeddings import ChunkEmbedding


@dataclass(frozen=True)
class VectorChunkResult:
    """
    Similarity result for one resume chunk.
    """

    chunk_id: str
    resume_id: str
    section: str
    score: float


@dataclass(frozen=True)
class VectorCandidateResult:
    """
    Aggregated semantic retrieval result for one candidate.
    """

    resume_id: str
    score: float
    matched_chunks: tuple[VectorChunkResult, ...]


class VectorRetriever:
    """
    FAISS-backed dense vector retriever.

    The index is built once from resume chunk embeddings and can then
    be queried repeatedly with job-description embeddings.

    Args:
        aggregation:
            Candidate-level aggregation strategy.
            Supported values: "max", "sum", "mean".
    """

    def __init__(
        self,
        aggregation: str = "max",
    ) -> None:
        allowed = {
            "max",
            "sum",
            "mean",
        }

        if aggregation not in allowed:
            raise ValueError(
                f"aggregation must be one of {sorted(allowed)}"
            )

        self.aggregation = aggregation

        self._index: faiss.Index | None = None
        self._embeddings: list[ChunkEmbedding] = []
        self._dimension: int | None = None

    @property
    def is_built(self) -> bool:
        """
        Return whether a FAISS index has been built.
        """
        return self._index is not None

    @property
    def dimension(self) -> int | None:
        """
        Return the dimension of the indexed vectors.
        """
        return self._dimension

    @staticmethod
    def cosine_similarity(
        query_vector: np.ndarray,
        document_vector: np.ndarray,
    ) -> float:
        """
        Calculate cosine similarity between two vectors.

        Retained for compatibility and unit testing.
        """
        query = np.asarray(
            query_vector,
            dtype=np.float32,
        ).reshape(-1)

        document = np.asarray(
            document_vector,
            dtype=np.float32,
        ).reshape(-1)

        if query.size == 0 or document.size == 0:
            raise ValueError(
                "vectors must not be empty"
            )

        if query.shape != document.shape:
            raise ValueError(
                "query and document vectors must have "
                "the same dimension"
            )

        if not np.all(np.isfinite(query)):
            raise ValueError(
                "query vector contains non-finite values"
            )

        if not np.all(np.isfinite(document)):
            raise ValueError(
                "document vector contains non-finite values"
            )

        query_norm = np.linalg.norm(query)
        document_norm = np.linalg.norm(document)

        if query_norm == 0 or document_norm == 0:
            return 0.0

        similarity = float(
            np.dot(query, document)
            / (query_norm * document_norm)
        )

        return similarity

    def build_index(
        self,
        embeddings: Sequence[ChunkEmbedding],
    ) -> None:
        """
        Build the FAISS vector index from resume chunk embeddings.

        The index uses inner-product similarity. Vectors are normalized
        before indexing so that inner product is equivalent to cosine
        similarity.

        Args:
            embeddings:
                Resume chunk embeddings generated by the embedding layer.
        """
        if not embeddings:
            self._index = None
            self._embeddings = []
            self._dimension = None
            return

        vectors = self._prepare_vectors(
            [embedding.vector for embedding in embeddings]
        )

        dimension = vectors.shape[1]

        index = faiss.IndexFlatIP(dimension)
        index.add(vectors)

        self._index = index
        self._embeddings = list(embeddings)
        self._dimension = dimension

    def score_chunks(
        self,
        query_vector: np.ndarray,
        embeddings: Sequence[ChunkEmbedding] | None = None,
    ) -> list[VectorChunkResult]:
        """
        Search the FAISS index and return chunk-level results.

        If embeddings are supplied, the index is rebuilt from them.
        This preserves compatibility with the previous API.

        For repeated production queries, build the index once with
        build_index() and omit embeddings here.
        """
        if embeddings is not None:
            self.build_index(embeddings)

        if not self.is_built:
            return []

        query = self._prepare_query(query_vector)

        total_vectors = self._index.ntotal

        scores, indices = self._index.search(
            query,
            total_vectors,
        )

        results: list[VectorChunkResult] = []

        for score, index_position in zip(
            scores[0],
            indices[0],
        ):
            if index_position < 0:
                continue

            embedding = self._embeddings[index_position]

            results.append(
                VectorChunkResult(
                    chunk_id=embedding.chunk_id,
                    resume_id=embedding.resume_id,
                    section=embedding.section,
                    score=float(score),
                )
            )

        results.sort(
            key=lambda result: (
                -result.score,
                result.chunk_id,
            )
        )

        return results

    def retrieve(
        self,
        query_vector: np.ndarray,
        embeddings: Sequence[ChunkEmbedding] | None = None,
        top_k: int = 10,
        min_score: float | None = None,
    ) -> list[VectorCandidateResult]:
        """
        Retrieve top semantically similar candidates.

        If embeddings are supplied, the FAISS index is rebuilt from them.
        For repeated queries against the same resume corpus, build the
        index once and call retrieve() without embeddings.

        Args:
            query_vector:
                Dense embedding for the JD/query.

            embeddings:
                Optional resume chunk embeddings. Used to build/rebuild
                the index for backward compatibility.

            top_k:
                Maximum number of candidates.

            min_score:
                Optional minimum cosine similarity.
        """
        if top_k < 0:
            raise ValueError(
                "top_k must be >= 0"
            )

        if min_score is not None and not (
            -1.0 <= min_score <= 1.0
        ):
            raise ValueError(
                "min_score must be between -1 and 1"
            )

        if top_k == 0:
            return []

        if embeddings is not None:
            self.build_index(embeddings)

        if not self.is_built:
            return []

        chunk_results = self.score_chunks(
            query_vector=query_vector,
        )

        if min_score is not None:
            chunk_results = [
                result
                for result in chunk_results
                if result.score >= min_score
            ]

        grouped: dict[
            str,
            list[VectorChunkResult],
        ] = {}

        for result in chunk_results:
            grouped.setdefault(
                result.resume_id,
                [],
            ).append(result)

        candidates: list[VectorCandidateResult] = []

        for resume_id, matched_chunks in grouped.items():
            score = self._aggregate(
                matched_chunks
            )

            matched_chunks.sort(
                key=lambda result: (
                    -result.score,
                    result.chunk_id,
                )
            )

            candidates.append(
                VectorCandidateResult(
                    resume_id=resume_id,
                    score=score,
                    matched_chunks=tuple(
                        matched_chunks
                    ),
                )
            )

        candidates.sort(
            key=lambda result: (
                -result.score,
                result.resume_id,
            )
        )

        return candidates[:top_k]

    def _aggregate(
        self,
        results: Sequence[VectorChunkResult],
    ) -> float:
        if not results:
            return 0.0

        scores = np.asarray(
            [result.score for result in results],
            dtype=np.float32,
        )

        if self.aggregation == "max":
            return float(np.max(scores))

        if self.aggregation == "sum":
            return float(np.sum(scores))

        return float(np.mean(scores))

    @staticmethod
    def _prepare_vectors(
        vectors: Sequence[np.ndarray],
    ) -> np.ndarray:
        """
        Convert vectors to a normalized float32 matrix.
        """
        matrix = np.asarray(
            vectors,
            dtype=np.float32,
        )

        if matrix.ndim != 2:
            raise ValueError(
                "embeddings must form a 2-dimensional matrix"
            )

        if matrix.shape[0] == 0:
            raise ValueError(
                "embeddings must not be empty"
            )

        if matrix.shape[1] == 0:
            raise ValueError(
                "embedding dimension must be greater than zero"
            )

        if not np.all(np.isfinite(matrix)):
            raise ValueError(
                "embeddings must contain only finite values"
            )

        normalized = matrix.copy()

        norms = np.linalg.norm(
            normalized,
            axis=1,
            keepdims=True,
        )

        zero_norms = norms.squeeze(axis=1) == 0

        if np.any(zero_norms):
            raise ValueError(
                "embeddings must not contain zero vectors"
            )

        normalized /= norms

        return np.ascontiguousarray(
            normalized,
            dtype=np.float32,
        )

    @staticmethod
    def _prepare_query(
        query_vector: np.ndarray,
    ) -> np.ndarray:
        """
        Validate and normalize a query vector for FAISS search.
        """
        query = np.asarray(
            query_vector,
            dtype=np.float32,
        ).reshape(1, -1)

        if query.shape[1] == 0:
            raise ValueError(
                "query vector must not be empty"
            )

        if not np.all(np.isfinite(query)):
            raise ValueError(
                "query vector contains non-finite values"
            )

        norm = np.linalg.norm(query)

        if norm == 0:
            raise ValueError(
                "query vector must not be a zero vector"
            )

        query /= norm

        return np.ascontiguousarray(
            query,
            dtype=np.float32,
        )


def retrieve_vectors(
    query_vector: np.ndarray,
    embeddings: Sequence[ChunkEmbedding],
    top_k: int = 10,
    aggregation: str = "max",
    min_score: float | None = None,
) -> list[VectorCandidateResult]:
    """
    Convenience function for vector retrieval.

    Builds a FAISS index for the supplied embeddings and performs
    one retrieval operation.
    """
    retriever = VectorRetriever(
        aggregation=aggregation,
    )

    return retriever.retrieve(
        query_vector=query_vector,
        embeddings=embeddings,
        top_k=top_k,
        min_score=min_score,
    )